development:
  secret_token: "my_secret_token"
  secret_key_base: "sk_test_QgDuytrwTVpbemzG69CWLikL"
production:
  secret_token:   <%= ENV["SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>